import{a as E,i as a,S as P}from"./assets/vendor-BWecv2LQ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v="https://pixabay.com/api/",I="47496497-c7088e577ab65ea786e483a4c";async function y(r,e,s){const n=new URLSearchParams({key:I,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s});try{return(await E.get(`${v}?${n}`)).data}catch{throw new Error("Error fetching images from API")}}function p(r){return r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" class="gallery_image">
      <div class="gallery-info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("")}const h=document.getElementById("search-form"),c=document.querySelector(".gallery"),b=document.getElementById("loader"),m=document.getElementById("load-more");let l="",i=1;const d=15;a.settings({timeout:1e3,color:"#EF4040",position:"topRight",titleColor:"#fff",messageColor:"#fff",imageWidth:24,iconColor:"#fff"});const w=new P(".gallery a");function L(){b.style.display="block"}function f(){b.style.display="none"}function B(){c.innerHTML=""}function g(){m.style.display="none"}function S(){m.style.display="block"}g();h.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.searchQuery.value.trim(),!l){a.warning({title:"Empty Field",message:"Please enter a search query."});return}i=1,B(),g(),L();try{const{hits:e,totalHits:s}=await y(l,i,d);f(),e.length>0?(c.innerHTML=p(e),w.refresh(),s>d&&S()):a.info({title:"No Results",message:"Sorry, there are no images matching your search query."})}catch{f(),a.error({title:"Error",message:"Something went wrong. Please try again later."})}h.reset()});m.addEventListener("click",async()=>{i+=1,L();try{const{hits:r,totalHits:e}=await y(l,i,d);if(f(),r.length>0){c.insertAdjacentHTML("beforeend",p(r)),w.refresh(),i*d>=e&&(g(),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}));const{height:n}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}catch{f(),a.error({title:"Error",message:"Something went wrong. Please try again later."})}});
//# sourceMappingURL=index.js.map
